# Generated by Django 4.1.2 on 2022-11-07 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='czarny', max_length=20)),
                ('invert', models.CharField(max_length=6)),
                ('sepia', models.CharField(max_length=6)),
                ('saturate', models.CharField(max_length=6)),
                ('hue_rotate', models.CharField(max_length=6)),
                ('brightness', models.CharField(max_length=6)),
                ('contrast', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('points', models.PositiveIntegerField(default=0)),
                ('people', models.PositiveIntegerField(default=0)),
                ('cash', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default='dd', max_length=40)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.color')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
