# Generated by Django 4.1.2 on 2022-11-03 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Big_Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('how_much_built', models.PositiveIntegerField(default=0)),
                ('size', models.PositiveIntegerField(default=4)),
                ('image', models.URLField(blank=True, default='https://ebilet-media.azureedge.net/media/18709/teatr-dom-git450.jpg', null=True)),
                ('patrol', models.TextField(blank=True, default='0', null=True)),
                ('cost', models.PositiveIntegerField(default=500)),
                ('generate_people', models.PositiveIntegerField(default=2)),
                ('generate_points', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('points', models.PositiveIntegerField(default=0)),
                ('people', models.PositiveIntegerField(default=0)),
                ('usedcodes', models.TextField(blank=True, default='', null=True)),
                ('built_buildings', models.TextField(blank=True, default='', null=True)),
                ('number_of_built_buildings', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('built', models.BooleanField(default=False)),
                ('image', models.URLField(blank=True, null=True)),
                ('cost', models.PositiveIntegerField(default=100)),
                ('generate_people', models.PositiveIntegerField(default=1)),
                ('generate_points', models.PositiveIntegerField(default=1)),
                ('patrol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patrol')),
            ],
        ),
    ]
