# Generated by Django 4.1.2 on 2022-11-07 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('base_points', models.IntegerField()),
                ('icon', models.ImageField(upload_to='building_imgs')),
                ('first_proximity_bonus', models.IntegerField()),
                ('second_proximity_bonus', models.IntegerField()),
                ('third_proximity_bonus', models.IntegerField()),
                ('fourth_proximity_bonus', models.IntegerField()),
                ('fifth_proximity_bonus', models.IntegerField()),
                ('sixth_proximity_bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CashCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_text', models.TextField(max_length=20)),
                ('cash_value', models.IntegerField(default=100)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.FileField(upload_to='plot_icons')),
                ('pic_position_x', models.IntegerField()),
                ('pic_position_y', models.IntegerField()),
                ('pic_height', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WrzeszczDev.building')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.color')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('plot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WrzeszczDev.plot')),
                ('bought_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WrzeszczDev.plot')),
                ('neighbour_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a', to='WrzeszczDev.plot')),
                ('neighbour_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b', to='WrzeszczDev.plot')),
                ('neighbour_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d', to='WrzeszczDev.plot')),
                ('neighbour_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c', to='WrzeszczDev.plot')),
                ('neighbour_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e', to='WrzeszczDev.plot')),
                ('neighbour_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f', to='WrzeszczDev.plot')),
            ],
        ),
    ]
