# Generated by Django 4.1.2 on 2022-11-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('WrzeszczDev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.TextField(max_length=20)),
                ('cash_value', models.IntegerField(default=100)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('building', models.IntegerField(default=0)),
                ('icon', models.ImageField(upload_to='')),
                ('pic_position_x', models.IntegerField()),
                ('pic_position_y', models.IntegerField()),
                ('pic_height', models.IntegerField()),
                ('pic_width', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patrol')),
            ],
        ),
    ]
